// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJhydnFTNb4uuTv2krkLDid_4Rb0o11yI',
    appId: '1:661268744436:android:cf2d7ed6b54412a70236a1',
    messagingSenderId: '661268744436',
    projectId: 'boxi-76550',
    storageBucket: 'boxi-76550.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnRlRVeffxl04nSU9oL_ygTsd2f178xWA',
    appId: '1:661268744436:ios:5cf5197839d152420236a1',
    messagingSenderId: '661268744436',
    projectId: 'boxi-76550',
    storageBucket: 'boxi-76550.appspot.com',
    iosClientId: '661268744436-vtdjs881ahnm9tk3fuqfo5kgtbni28aj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
